version: '3.8'

# 初始化组件/环境
# docker-compose -f minio-compose.yml up -d

services:
  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: minio
    restart: always
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # 控制台
    environment:
      # 账号密码
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio123
      # API 接口地址
      #MINIO_SERVER_URL: http://minio.vains.ddns-ip.net:20000
      # 控制台访问地址
      MINIO_BROWSER_REDIRECT_URL: http://minio.vains.ddns-ip.net:20000/ui
    command: server /data --console-address ":9001"
    volumes:
      - /opt/docker/minio/data:/data

