spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/basic-platform?serverTimezone=Asia/Shanghai&userUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      database: 6

springdoc:
  show-login-endpoint: true
server:
  port: 10000
  # 使用底层容器的转发头策略
  forward-headers-strategy: native

# Mybatis Plus相关配置
mybatis-plus:
  # mapper文件位置
  mapper-locations: classpath*:/mapper/**/*.xml,classpath:com/basic/mapper/xml/*.xml