spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/basic-platform?serverTimezone=Asia/Shanghai&userUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}

springdoc:
  show-login-endpoint: true
server:
  port: 10000

# Mybatis Plus相关配置
mybatis-plus:
  # mapper文件位置
  mapper-locations: classpath*:/mapper/**/*.xml,classpath:com/basic/mapper/xml/*.xml

logging:
  level:
    # 打印SQL
    com.basic.mapper: debug