spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:192.168.1.3}:${DB_PORT:3306}/basic-platform?serverTimezone=Asia/Shanghai&userUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  data:
    redis:
      url: ${REDIS_URL:redis://192.168.1.3:6379/6}

  mail:
    host: smtp.163.com
    port: 25
    username: 17683906991@163.com
    password: ${MAIL_PASSWORD}

springdoc:
  show-login-endpoint: true
server:
  port: 10000
  tomcat:
    remoteip:
      protocol-header: X-Forwarded-Proto

# Mybatis Plus相关配置
mybatis-plus:
  # mapper文件位置
  mapper-locations: classpath*:/mapper/**/*.xml,classpath:com/basic/mapper/xml/*.xml+

basic:
  cloud:
    cors:
      # 允许跨域地址
      allowed-origins:
        - http://localhost:5173
        - http://127.0.0.1:5173

    security:
      token:
        access-token-expire: 7200
        refresh-token-expire: 7
        issuer: basic-server

      login:
        # 前端页面地址
        front-end-url: http://127.0.0.1:5173

    # minio 配置
    minio:
      bucket: basic-platform
      endpoint: http://${SERVER_URL}:9000
      access-key: ${MINIO_ACCESS_KEY}
      secret-key: ${MINIO_SECRET_KEY}
      proxy-endpoint: http://minio.vains.ddns-ip.net:20000/