server {
    # 启用 IPv6 支持
    listen [::]:20000; 
	# 同时支持 IPv4
    listen 20000;  
    #绑定证书的域名
    server_name basic.vains.ddns-ip.net; 
	
	# ddns自动解析
    location / {
        # 设置允许嵌入的域名
		add_header X-Frame-Options "ALLOW-FROM http://web.vains.ddns-ip.net:20000";
		add_header Content-Security-Policy "frame-ancestors http://web.vains.ddns-ip.net:20000";

		# 代理地址
		proxy_pass http://127.0.0.1:10000;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}