map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {

    listen 20000;
    listen [::]:20000;

    server_name minio.vains.ddns-ip.net;

    client_max_body_size 10G;

    # MinIO API
    location / {

        proxy_pass http://127.0.0.1:9000/;

        proxy_http_version 1.1;
        # 非80/433端口的Host用 $http_host 代替 $host
        proxy_set_header Host $http_host;

        proxy_set_header Connection "";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_request_buffering off;
    }

    # MinIO Console
    location /ui/ {

        proxy_pass http://127.0.0.1:9001/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_buffering off;
    }
}