server {
    # 启用 IPv6 支持
    listen [::]:20000; 
	# 同时支持 IPv4
    listen 20000;  
    #绑定证书的域名
    server_name basic.vains.ddns-ip.net; 
	
	# ddns自动解析
    location / {
		proxy_pass http://127.0.0.1:10000;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}